import Head from "next/head";
import styles from "@/styles/Home.module.css";
import CoinList from "@/components/CoinList";
import { useState } from "react";


export default function Home() {
  const [favorites, setFavorites] = useState<string[]>([]); 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <CoinList  />
      </main>
    </>
  );
}
